// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'BLACK': string;
  'BLUE': string;
  'BOLD_PURPLE': string;
  'DARK_GRAY': string;
  'DARK_GREY': string;
  'GRAY': string;
  'GREEN': string;
  'GREY': string;
  'INDICATOR_BLUE': string;
  'LIGHT_GRAY': string;
  'LIGHT_GREY': string;
  'OFF_WHITE': string;
  'ORANGE': string;
  'PURPLE': string;
  'RED': string;
  'ROSE': string;
  'VERY_LIGHT_GRAY': string;
  'VERY_LIGHT_GREY': string;
  'WHITE': string;
  'YELLOW': string;
}
export const cssExports: CssExports;
export default cssExports;
