// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'BLACK': string;
  'DARK_GRAY': string;
  'DARK_GREY': string;
  'GRAY': string;
  'GREY': string;
  'LIGHT_GRAY': string;
  'LIGHT_GREY': string;
  'WHITE': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
